name: CD - Deploy Backend Services to AKS

on:
  workflow_dispatch:
    inputs:
      aks_cluster_name:
        description: 'Name of the AKS Cluster to deploy to'
        required: true
        default: 'danuth-aks'
      aks_resource_group:
        description: 'Resource Group of the AKS Cluster'
        required: true
        default: 'danuth-rsg'
      aks_acr_name:
        description: 'Name of ACR'
        required: true
        default: 'danuthacr'

jobs:
  deploy-backend-services:
    strategy:
      matrix:
        service: [product, order]
    uses: ./.github/workflows/_deploy-backend.yml
    with:
      service: ${{ matrix.service }}
      aks_cluster_name: ${{ github.event.inputs.aks_cluster_name }}
      aks_resource_group: ${{ github.event.inputs.aks_resource_group }}
      aks_acr_name: ${{ github.event.inputs.aks_acr_name }}
    secrets: inherit
